version: '3'
services:

  #PHP Service
  squad-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: makutachi/squad-service:latest
    container_name: squad-service
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    environment:
      SERVICE_NAME: squad-service
      SERVICE_TAGS: dev
    working_dir: /app
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: squad
      MYSQL_ROOT_PASSWORD: 12345678
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  #Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    tty: true
    command: redis-server 
    ports:
      - "6379:6379"
    environment:
      REDIS_REPLICATION_MODE: master
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - app-network

  #Redis Service
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
