version: '3'
services:

  #PHP Service
  squad-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: makutachi/squad-service:latest
    container_name: squad-service
    restart: unless-stopped
    tty: true
    ports:
      - "8080:8080"
    environment:
      SERVICE_NAME: squad-service
      SERVICE_TAGS: dev
    working_dir: /app
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: squad
      MYSQL_ROOT_PASSWORD: 12345678
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network


#Docker Networks
networks:
  app-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
